# Generated by Django 5.1 on 2025-11-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysubmissioncount',
            name='bonus_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
